apiVersion: v1
kind: Namespace
metadata:
  name: ${cluster_namespace}
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials-secret
  namespace: ${cluster_namespace}
type: Opaque
data:
  awsAccessKeyId:
  awsSecretAccessKey:
