---
apiVersion: cluster.k8s.io/v1alpha1
kind: MachineSet
metadata:
  name: aws-actuator-testing-machine
  namespace: ${cluster_namespace}
  labels:
    sigs.k8s.io/cluster-api-cluster: ${cluster_name}
    sigs.k8s.io/cluster-api-machine-role: infra
    sigs.k8s.io/cluster-api-machine-type: master
spec:
  replicas: 2
  selector:
    matchLabels:
      sigs.k8s.io/cluster-api-machineset: ${cluster_name}-master
      sigs.k8s.io/cluster-api-cluster: ${cluster_name}
  template:
    metadata:
      labels:
        sigs.k8s.io/cluster-api-machineset: ${cluster_name}-master
        sigs.k8s.io/cluster-api-cluster: ${cluster_name}
        sigs.k8s.io/cluster-api-machine-role: infra
        sigs.k8s.io/cluster-api-machine-type: master
    spec:
      providerConfig:
        value:
          apiVersion: aws.cluster.k8s.io/v1alpha1
          kind: AWSMachineProviderConfig
          ami:
            # id: ami-060f14ef82deddfc6
            filters:
            - name: "image_stage"
              values:
              - "base"
            - name: operating_system
              values:
              - "rhel"
            - name: ready
              values:
              - "yes"
          credentialsSecret:
            name: aws-credentials-secret
          instanceType: m4.xlarge
          placement:
            region: ${aws_region}
            availabilityZone: ${aws_availability_zone}
          iamInstanceProfile:
            id: openshift_master_launch_instances
          keyName: ${ssh_key_name}
          tags:
            - name: openshift-node-group-config
              value: node-config-master
            - name: host-type
              value: master
            - name: sub-host-type
              value: default
          securityGroups:
            - id: ${cluster_security_group}
          publicIP: true
