apiVersion: v1
kind: Namespace
metadata:
  name: test
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials-secret
  namespace: test
type: Opaque
data:
  awsAccessKeyId:
  awsSecretAccessKey:
