---
apiVersion: "cluster.k8s.io/v1alpha1"
kind: Machine
metadata:
  name: aws-actuator-testing-machine
  namespace: test
  generateName: vs-worker-
  labels:
    machine.openshift.io/cluster-api-cluster: tb-asg-35
    machine.openshift.io/cluster-api-machine-role: compute
    machine.openshift.io/cluster-api-machine-type: worker
spec:
  providerSpec:
    value:
      apiVersion: awsproviderconfig.k8s.io/v1alpha1
      kind: AWSMachineProviderConfig
      ami:
        filters:
        - name: "image_stage"
          values:
          - "base"
        - name: operating_system
          values:
          - "rhel"
        - name: ready
          values:
          - "yes"
      instanceType: m4.large
      placement:
        region: eu-west-1
        availabilityZone: eu-west-1c
      subnet:
        filters:
        - name: "tag:Name"
          values:
          - "meh-worker-eu-west-1c"
      publicIp: true
      iamInstanceProfile:
        id: meh-master-profile
      keyName: tectonic
      tags:
      - name: "kubernetes.io/cluster/meh"
        value: owned
      securityGroups:
      - filters:
        - name: "tag:Name"
          values:
          - "meh_worker_sg"
      userDataSecret:
        name: ignition-worker
  versions:
    kubelet: ""
    controlPlane: ""
