---
apiVersion: "cluster.k8s.io/v1alpha1"
kind: Machine
metadata:
  name: aws-actuator-testing-machine-master
  namespace: test
  generateName: vs-master-
  labels:
    sigs.k8s.io/cluster-api-cluster: tb-asg-35
    sigs.k8s.io/cluster-api-machine-role: infra
    sigs.k8s.io/cluster-api-machine-type: master
spec:
  providerConfig:
    value:
      apiVersion: aws.cluster.k8s.io/v1alpha1
      kind: AWSMachineProviderConfig
      ami:
        filters:
        - name: "tag:image_stage"
          values:
          - "base"
        - name: "tag:operating_system"
          values:
          - "rhel"
        - name: "tag:ready"
          values:
          - "yes"
      instanceType: m4.xlarge
      placement:
        region: us-east-1
        availabilityZone: us-east-1a
      subnet:
        filters:
          - name: "tag:Name"
            values:
            - "{{ .ClusterID }}-worker-*"
      iamInstanceProfile:
        id: openshift_master_launch_instances
      keyName: libra
      tags:
      - name: openshift-node-group-config
        value: node-config-master
      - name: host-type
        value: master
      - name: sub-host-type
        value: default
      securityGroups:
        - filters:
            - name: "tag:Name"
              values:
              - "{{ .ClusterID }}-*"
      publicIp: true
      userDataSecret:
        name: aws-actuator-master-user-data-secret
  versions:
    kubelet: 1.10.1
    controlPlane: 1.10.1
